import {
  Factory,
  FlaskConical,
  LineChart,
  Cpu,
  Gauge,
  Zap,
  Droplets,
  Pipette,
  Wrench,
  Package,
  Fuel,
  Mountain,
  Atom,
  Leaf,
  Building2,
  Microscope,
  Beaker,
  Home,
  Search,
  MessageSquare,
  FileText,
  ShieldCheck,
  Settings,
  Truck,
  BookOpen,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  factory: Factory,
  lab: FlaskConical,
  analytics: LineChart,
  automation: Cpu,
  instruments: Gauge,
  electric: Zap,
  pump: Droplets,
  valve: Pipette,
  engineering: Wrench,
  supply: Package,
  oil: Fuel,
  energy: Zap,
  metal: Factory,
  mining: Mountain,
  chemical: Atom,
  eco: Leaf,
  construction: Building2,
  science: Beaker,
  utilities: Home,
  selection: Search,
  consulting: MessageSquare,
  project: FileText,
  warranty: ShieldCheck,
  service: Settings,
  logistics: Truck,
  docs: BookOpen,
};

export function getIcon(name: string): LucideIcon {
  return iconMap[name] ?? Wrench;
}
